Temporarily add rpm-build install

diff --git a/.github/workflows/compose-tests.yml b/.github/workflows/compose-tests.yml
--- a/.github/workflows/compose-tests.yml
+++ b/.github/workflows/compose-tests.yml
@@ -60,6 +60,20 @@ jobs:
         uses: actions/checkout@v6
         with:
           ref: ${{ inputs.ref || github.sha }}
+      # TODO: remove this once added to the runners
+      - name: Install RPM build tools
+        run: |
+          if command -v rpmbuild >/dev/null 2>&1; then
+            exit 0
+          elif command -v dnf >/dev/null 2>&1; then
+            sudo dnf install -y rpm-build
+          elif command -v apt-get >/dev/null 2>&1; then
+            sudo apt-get update
+            sudo apt-get install -y rpm
+          else
+            echo "::error::Unsupported package manager"
+            exit 1
+          fi
       # Clean up free space
       - uses: ./.github/actions/free-space
         with:
