Re-run full test suite explicitly on failure.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -56,7 +56,11 @@ jobs:
           ${{ runner.os }}-maven-format-
           ${{ runner.os }}-maven-
     - name: Build and Run Unit Tests
-      run: mvn -V -B -e -Dsurefire.rerunFailingTestsCount=3 -Pdev,examples,assemble -Ddist -T1C clean verify
+      run: |
+        RUN_TESTS="mvn -V -B -e Pdev,examples,assemble -Ddist -T1C clean verify"
+        $RUN_TESTS \
+          || { echo "***** TESTS FAILED. Attempting retry."; $RUN_TESTS; } \
+          || { echo "***** TESTS FAILED. Attempting final retry."; $RUN_TESTS; }
       env:
         MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Djava.awt.headless=true"
 
