make github action tests match integration

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -6,7 +6,6 @@ on:
     branches:
     - 'integration'
     - 'release/version*'
-    - 'feature/queryMicroservices'
   pull_request:
     paths-ignore: ['*.md', 'CODEOWNERS', 'LICENSE']
   workflow_dispatch:
@@ -57,8 +56,6 @@ jobs:
     steps:
     - name: Checkout Code
       uses: actions/checkout@v3
-      with:
-        submodules: 'recursive'
     - name: Set up JDK ${{env.JAVA_VERSION}}
       uses: actions/setup-java@v3
       with:
@@ -76,57 +73,55 @@ jobs:
           || { echo "***** TESTS FAILED. Attempting retry."; $RUN_TESTS; } \
           || { echo "***** TESTS FAILED. Attempting final retry."; $RUN_TESTS; }
 
-  # This step can be uncommented to support feature development.  When developing a
-  # feature which spans multiple repos, you can update the poms to use the latest
-  # SNAPSHOT across the board, and run this action as a sanity check to ensure
+  # This step can be uncommented to support feature development.  When developing a 
+  # feature which spans multiple repos, you can update the poms to use the latest 
+  # SNAPSHOT across the board, and run this action as a sanity check to ensure 
   # everything is working in unison.
 
-  # Build the code and run the microservice unit/integration tests.
-  build-and-test-microservices:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v3
-        with:
-          submodules: 'recursive'
-      - name: Set up JDK ${{env.JAVA_VERSION}}
-        uses: actions/setup-java@v3
-        with:
-          distribution: ${{env.JAVA_DISTRIBUTION}}
-          java-version: ${{env.JAVA_VERSION}}
-      - uses: actions/cache@v3
-        with:
-          path: ~/.m2/repository
-          key: ${{ runner.os }}-maven-build-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            ${{ runner.os }}-maven-build-
-            ${{ runner.os }}-maven-format-
-            ${{ runner.os }}-maven-
-      - name: Build Project
-        env:
-          USER_NAME: ${{ secrets.USER_NAME }}
-          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
-        run: |
-          BUILD="mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -V -B -e -Pdev,examples,assemble,spotbugs -DskipServices -Dmaven.build.cache.enabled=false -Ddeploy -Ddist -T1C -pl "-:config-service" clean install -DskipTests"
-          $BUILD
-      - name: Run Microservice Unit Tests
-        env:
-          USER_NAME: ${{ secrets.USER_NAME }}
-          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
-        run: |
-          RUN_TESTS="mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -V -B -e verify"
-          cd microservices
-          $RUN_TESTS \
-            || { echo "***** TESTS FAILED. Attempting retry."; $RUN_TESTS; } \
-            || { echo "***** TESTS FAILED. Attempting final retry."; $RUN_TESTS; }
+  # # Build the code and run the microservice unit/integration tests.
+  # build-and-test-microservices:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout Code
+  #       uses: actions/checkout@v3
+  #       with:
+  #         submodules: 'recursive'
+  #     - name: Set up JDK ${{env.JAVA_VERSION}}
+  #       uses: actions/setup-java@v3
+  #       with:
+  #         distribution: ${{env.JAVA_DISTRIBUTION}}
+  #         java-version: ${{env.JAVA_VERSION}}
+  #     - uses: actions/cache@v3
+  #       with:
+  #         path: ~/.m2/repository
+  #         key: ${{ runner.os }}-maven-build-${{ hashFiles('**/pom.xml') }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-maven-build-
+  #           ${{ runner.os }}-maven-format-
+  #           ${{ runner.os }}-maven-
+  #     - name: Build Project
+  #       env:
+  #         USER_NAME: ${{ secrets.USER_NAME }}
+  #         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
+  #       run: |
+  #         BUILD="mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -V -B -e -Pdev,examples,assemble,spotbugs -Dmaven.build.cache.enabled=false -DskipServices -Ddeploy -Ddist -T1C -pl "-:config-service" clean install -DskipTests"
+  #         $BUILD
+  #     - name: Run Microservice Unit Tests
+  #       env:
+  #         USER_NAME: ${{ secrets.USER_NAME }}
+  #         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
+  #       run: |
+  #         RUN_TESTS="mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -V -B -e -Dmaven.build.cache.enabled=false verify"
+  #         cd microservices
+  #         $RUN_TESTS \
+  #           || { echo "***** TESTS FAILED. Attempting retry."; $RUN_TESTS; } \
+  #           || { echo "***** TESTS FAILED. Attempting final retry."; $RUN_TESTS; }
 
   quickstart-build-and-test:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout Code
       uses: actions/checkout@v3
-      with:
-        submodules: 'recursive'
     - name: Set up JDK ${{env.JAVA_VERSION}}
       uses: actions/setup-java@v3
       with:
@@ -147,91 +142,13 @@ jobs:
     # Builds the quickstart docker image and run the query tests
     - name: Quickstart Query Tests
       env:
-        DW_DATAWAVE_BUILD_COMMAND: "mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -B -V -e -ntp -Dstyle.color=always -Dmaven.build.cache.enabled=false -Pdev -DskipServices -Ddeploy -Dtar -DskipTests -pl -:config-service clean package"
+        DW_DATAWAVE_BUILD_COMMAND: "mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -B -V -e -ntp -Dstyle.color=always -Dmaven.build.cache.enabled=false -Pdev -Ddeploy -Dtar -DskipTests clean package"
         DOCKER_BUILD_OPTS: "--squash --force-rm"
         USER_NAME: ${{ secrets.USER_NAME }}
         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
       run: |
         TAG=$(mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -q -N -Dmaven.build.cache.enabled=false -Dexec.executable='echo' -Dexec.args='${project.version}' exec:exec)
         contrib/datawave-quickstart/docker/docker-build.sh ${TAG} --docker-opts "${DOCKER_BUILD_OPTS}"
-
-  compose-build-and-test:
-    runs-on: ubuntu-latest
-    steps:
-    - name: Free up some space
-      run: |
-        sudo rm -rf /usr/share/dotnet
-        sudo rm -rf /opt/ghc
-        sudo rm -rf /usr/local/share/boost
-        sudo rm -rf $AGENT_TOOLSDIRECTORY
-    - name: Checkout Code
-      uses: actions/checkout@v3
-      with:
-        submodules: 'recursive'
-    - name: Set up JDK ${{env.JAVA_VERSION}}
-      uses: actions/setup-java@v3
-      with:
-        distribution: ${{env.JAVA_DISTRIBUTION}}
-        java-version: ${{env.JAVA_VERSION}}
-    - uses: actions/cache@v3
-      with:
-        path: ~/.m2/repository
-        key: ${{ runner.os }}-maven-build-${{ hashFiles('**/pom.xml') }}
-        restore-keys: |
-          ${{ runner.os }}-maven-build-
-          ${{ runner.os }}-maven-format-
-          ${{ runner.os }}-maven-
-    # Builds the quickstart and microservice docker images and runs a query test
-    - name: Docker Compose Query Tests
-      env:
-        USER_NAME: ${{ secrets.USER_NAME }}
-        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
-      run: |
-        mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -B -V -e -Pcompose -Dmicroservice-docker -Dquickstart-docker -Ddeploy -Dtar -DskipTests clean install
-        
-        # free up some space so that we don't run out
-        docker system prune -f
-        mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -B -V -e -Pcompose -Dmicroservice-docker -Dquickstart-docker -Ddeploy -Dtar -DskipTests clean
-        
-        cd docker
-        ./bootstrap.sh
-
-        attempt=0
-        max_attempts=20
-        while [ $attempt -lt $max_attempts ]; do
-          attempt=$((attempt+1))
-
-          echo "Starting docker compose (Attempt ${attempt}/${max_attempts})"
-          nohup docker compose up -d --no-recreate < /dev/null > compose.out 2>&1 &
-          sleep 60s
-          cat compose.out
-        
-          # check to see if the query service is running
-          QUERY="$(docker compose ps --status running --services | grep query || true)"
-
-          if [ "$QUERY" == "query" ] ; then
-            echo "Docker compose started successfully"
-            break
-          elif [ $attempt -eq $max_attempts ] ; then
-            echo "Failed to start docker compose"
-            exit 1
-          fi
-        done
-
-        cd scripts
-        ./testAll.sh
-
-    - name: Dump Logs
-      if: failure()
-      run: |
-        cd docker
-        docker compose logs
-
-    - name: Docker Compose Cleanup
-      if: always()
-      run: |
-        cd docker
-        docker compose down -v --remove-orphans
 
     # Here's an example of how you'd deploy the image to the github package registry.
     # We don't want to do this by default since packages on github cannot be deleted
@@ -254,4 +171,3 @@ jobs:
     #     docker tag ${IMAGE_NAME}:${TAG} ${REMOTE_IMAGE_NAME}:${TAG}
     #     docker images
     #     docker push ${REMOTE_IMAGE_NAME}:${TAG}
-
