Revert "Recombined microservice and core github ci tests to decrease CI job runtime"
This reverts commit ec1726066a5b2e552d263cc18d58d1f69c943f02.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -44,8 +44,43 @@ jobs:
       env:
         MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Djava.awt.headless=true"
 
-  # Build the code and run the unit/integration tests.
+  # Build the code and run the core unit/integration tests.
   build-and-test:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout Code
+      uses: actions/checkout@v2
+      with:
+        submodules: 'recursive'
+    - name: Set up JDK 1.8
+      uses: actions/setup-java@v1
+      with:
+        java-version: 1.8
+    - uses: actions/cache@v1
+      with:
+        path: ~/.m2/repository
+        key: ${{ runner.os }}-maven-build-${{ hashFiles('**/pom.xml') }}
+        restore-keys: |
+          ${{ runner.os }}-maven-build-
+          ${{ runner.os }}-maven-format-
+          ${{ runner.os }}-maven-
+    - name: Build Project
+      run: |
+        BUILD="mvn -V -B -e -Pdev,examples,assemble,spotbugs -Ddeploy -Ddist -T1C clean install -DskipTests"
+        $BUILD
+      env:
+        MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Djava.awt.headless=true"
+    - name: Run Core Unit Tests
+      run: |
+        RUN_TESTS="mvn -V -B -e -Pdev,examples,assemble,spotbugs -DskipMicroservices -Ddeploy -Ddist -T1C verify"
+        $RUN_TESTS \
+          || { echo "***** TESTS FAILED. Attempting retry."; $RUN_TESTS; } \
+          || { echo "***** TESTS FAILED. Attempting final retry."; $RUN_TESTS; }
+      env:
+        MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Djava.awt.headless=true"
+
+  # Build the code and run the microservice unit/integration tests.
+  build-and-test-microservices:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
@@ -64,10 +99,17 @@ jobs:
             ${{ runner.os }}-maven-build-
             ${{ runner.os }}-maven-format-
             ${{ runner.os }}-maven-
-      # QueryMetricSplitBrainMergePolicyTest always fails in GitHub CI (presumably due to resource limits), so we will skip it
-      - name: Build and Run Unit Tests
+      - name: Build Project
         run: |
-          RUN_TESTS="mvn -V -B -e -Pdev,examples,assemble,spotbugs -DskipSplitBrainTest -Ddeploy -Ddist -T1C clean verify"
+          BUILD="mvn -V -B -e -Pdev,examples,assemble,spotbugs -Ddeploy -Ddist -T1C clean install -DskipTests"
+          $BUILD
+        env:
+          MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Djava.awt.headless=true"
+      # QueryMetricSplitBrainMergePolicyTest always fails in GitHub CI (presumably due to resource limits), so we will skip it
+      - name: Run Microservice Unit Tests
+        run: |
+          RUN_TESTS="mvn -V -B -e -DskipSplitBrainTest verify"
+          cd microservices
           $RUN_TESTS \
             || { echo "***** TESTS FAILED. Attempting retry."; $RUN_TESTS; } \
             || { echo "***** TESTS FAILED. Attempting final retry."; $RUN_TESTS; }
