task/GITHUB-2414 GitHub action update

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -2,14 +2,15 @@ name: Tests
 
 on:
   push:
-    paths-ignore: ['*.md', 'CODEOWNERS', 'LICENSE']
+    paths-ignore: [ '*.md', 'CODEOWNERS', 'LICENSE' ]
     branches:
-    - 'integration'
-    - 'release/version*'
+      - 'integration'
+      - 'release/version*'
+      - 'task/GITHUB-2414'
   pull_request:
-    paths-ignore: ['*.md', 'CODEOWNERS', 'LICENSE']
+    paths-ignore: [ '*.md', 'CODEOWNERS', 'LICENSE' ]
   workflow_dispatch:
-  
+
 env:
   JAVA_VERSION: '11'
   JAVA_DISTRIBUTION: 'zulu' #This is the default on v1 of the action for 1.8
@@ -22,133 +23,184 @@ jobs:
   check-code-formatting:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout Code
-      uses: actions/checkout@v3
-    - name: Set up JDK ${{env.JAVA_VERSION}}
-      uses: actions/setup-java@v3
-      with:
-        distribution: ${{env.JAVA_DISTRIBUTION}}
-        java-version: ${{env.JAVA_VERSION}}
-        maven-version: 3.9.5
-        cache: 'maven'
-    - name: Format code
-      env:
-        USER_NAME: ${{ secrets.USER_NAME }}
-        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
-      run: |
-        mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -V -B -e -ntp "-Dstyle.color=always" clean formatter:format sortpom:sort impsort:sort -Dmaven.build.cache.enabled=false -Pautoformat
-        git status
-        git diff-index --quiet HEAD || (echo "Modified files found. Creating new commit with formatting fixes" && echo "diffs_found=true" >> "$GITHUB_ENV")
-    - name: Commit Changes
-      run: |
-        if [ "$diffs_found" = true ]; then
-          git config --global user.name "GitHub Actions"
-          git config --global user.email "datawave@github.com"
-          git commit -am "Formatting job fix"
-          git push
-        else
-          echo "Nothing to do"
-        fi
-        
+      - name: Checkout Code
+        uses: actions/checkout@v3
+      - name: Set up JDK ${{env.JAVA_VERSION}}
+        uses: actions/setup-java@v3
+        with:
+          distribution: ${{env.JAVA_DISTRIBUTION}}
+          java-version: ${{env.JAVA_VERSION}}
+          maven-version: 3.9.5
+          cache: 'maven'
+      - name: Format code
+        env:
+          USER_NAME: ${{ secrets.USER_NAME }}
+          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
+        run: |
+          mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -V -B -e -ntp "-Dstyle.color=always" clean formatter:format sortpom:sort impsort:sort -Dmaven.build.cache.enabled=false -Pautoformat
+          git status
+          git diff-index --quiet HEAD || (echo "Modified files found. Creating new commit with formatting fixes" && echo "diffs_found=true" >> "$GITHUB_ENV")
+      - name: Commit Changes
+        run: |
+          if [ "$diffs_found" = true ]; then
+            git config --global user.name "GitHub Actions"
+            git config --global user.email "datawave@github.com"
+            git commit -am "Formatting job fix"
+            git push
+          else
+            echo "Nothing to do"
+          fi
+
   # Build the code and run the unit/integration tests.
   build-and-test:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout Code
-      uses: actions/checkout@v3
-    - name: Set up JDK ${{env.JAVA_VERSION}}
-      uses: actions/setup-java@v3
-      with:
-        distribution: ${{env.JAVA_DISTRIBUTION}}
-        java-version: ${{env.JAVA_VERSION}}
-        maven-version: 3.9.5
-        cache: 'maven'
-    - name: Build and Run Unit Tests
-      env:
-        USER_NAME: ${{ secrets.USER_NAME }}
-        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
-      run: |
-        RUN_TESTS="mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -V -B -e -ntp "-Dstyle.color=always" -Pdev,examples,assemble,spotbugs -Dmaven.build.cache.enabled=false -Ddeploy -Ddist -T1C clean verify"
-        $RUN_TESTS \
-          || { echo "***** TESTS FAILED. Attempting retry."; $RUN_TESTS; } \
-          || { echo "***** TESTS FAILED. Attempting final retry."; $RUN_TESTS; }
+      - name: Checkout Code
+        uses: actions/checkout@v3
+      - name: Set up JDK ${{env.JAVA_VERSION}}
+        uses: actions/setup-java@v3
+        with:
+          distribution: ${{env.JAVA_DISTRIBUTION}}
+          java-version: ${{env.JAVA_VERSION}}
+          maven-version: 3.9.5
+          cache: 'maven'
+      - name: Build and Run Unit Tests
+        env:
+          USER_NAME: ${{ secrets.USER_NAME }}
+          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
+        run: |
+          RUN_TESTS="mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -V -B -e -ntp "-Dstyle.color=always" -Pdev,examples,assemble,spotbugs -Dmaven.build.cache.enabled=false -Ddeploy -Ddist -T1C clean verify"
+          $RUN_TESTS \
+            || { echo "***** TESTS FAILED. Attempting retry."; $RUN_TESTS; } \
+            || { echo "***** TESTS FAILED. Attempting final retry."; $RUN_TESTS; }
+              # Starts up docker services and runs test queries
+      - name: Start up docker quickstart services and run test
+        env:
+          USER_NAME: ${{ secrets.USER_NAME }}
+          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
+        run: docker-compose -f docker/docker-compose.yml up -d
+      - name: Run TestAll script
+        env:
+          USER_NAME: ${{ secrets.USER_NAME }}
+          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
+        run: |
+          docker-compose -f docker/docker-compose.yml exec web docker/scripts/testall.sh || echo "Tests failed"
 
-  # This step can be uncommented to support feature development.  When developing a 
-  # feature which spans multiple repos, you can update the poms to use the latest 
-  # SNAPSHOT across the board, and run this action as a sanity check to ensure 
-  # everything is working in unison.
+    # This step can be uncommented to support feature development.  When developing a
+    # feature which spans multiple repos, you can update the poms to use the latest
+    # SNAPSHOT across the board, and run this action as a sanity check to ensure
+    # everything is working in unison.
 
-  # # Build the code and run the microservice unit/integration tests.
-  # build-and-test-microservices:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout Code
-  #       uses: actions/checkout@v3
-  #       with:
-  #         submodules: 'recursive'
-  #     - name: Set up JDK ${{env.JAVA_VERSION}}
-  #       uses: actions/setup-java@v3
-  #       with:
-  #         distribution: ${{env.JAVA_DISTRIBUTION}}
-  #         java-version: ${{env.JAVA_VERSION}}
-  #     - uses: actions/cache@v3
-  #       with:
-  #         path: ~/.m2/repository
-  #         key: ${{ runner.os }}-maven-build-${{ hashFiles('**/pom.xml') }}
-  #         restore-keys: |
-  #           ${{ runner.os }}-maven-build-
-  #           ${{ runner.os }}-maven-format-
-  #           ${{ runner.os }}-maven-
-  #     - name: Build Project
-  #       env:
-  #         USER_NAME: ${{ secrets.USER_NAME }}
-  #         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
-  #       run: |
-  #         BUILD="mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -V -B -e -Pdev,examples,assemble,spotbugs -Dmaven.build.cache.enabled=false -DskipServices -Ddeploy -Ddist -T1C -pl "-:config-service" clean install -DskipTests"
-  #         $BUILD
-  #     - name: Run Microservice Unit Tests
-  #       env:
-  #         USER_NAME: ${{ secrets.USER_NAME }}
-  #         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
-  #       run: |
-  #         RUN_TESTS="mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -V -B -e -Dmaven.build.cache.enabled=false verify"
-  #         cd microservices
-  #         $RUN_TESTS \
-  #           || { echo "***** TESTS FAILED. Attempting retry."; $RUN_TESTS; } \
-  #           || { echo "***** TESTS FAILED. Attempting final retry."; $RUN_TESTS; }
+    # Build the code and run the microservice unit/integration tests.
+    build-and-test-microservices:
+      runs-on: ubuntu-latest
+      steps:
+        - name: Checkout Code
+          uses: actions/checkout@v3
+          with:
+            submodules: 'recursive'
+        - name: Set up JDK ${{env.JAVA_VERSION}}
+          uses: actions/setup-java@v3
+          with:
+            distribution: ${{env.JAVA_DISTRIBUTION}}
+            java-version: ${{env.JAVA_VERSION}}
+        - uses: actions/cache@v3
+          with:
+            path: ~/.m2/repository
+            key: ${{ runner.os }}-maven-build-${{ hashFiles('**/pom.xml') }}
+            restore-keys: |
+              ${{ runner.os }}-maven-build-
+              ${{ runner.os }}-maven-format-
+              ${{ runner.os }}-maven-
+        - name: Build Project
+          env:
+            USER_NAME: ${{ secrets.USER_NAME }}
+            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
+          run: |
+            BUILD="mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -V -B -e -Pdev,examples,assemble,spotbugs -Dmaven.build.cache.enabled=false -DskipServices -Ddeploy -Ddist -T1C -pl "-:config-service" clean install -DskipTests"
+            $BUILD
+        - name: Run Microservice Unit Tests
+          env:
+            USER_NAME: ${{ secrets.USER_NAME }}
+            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
+          run: |
+            RUN_TESTS="mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -V -B -e -Dmaven.build.cache.enabled=false verify"
+            cd microservices
+            $RUN_TESTS \
+              || { echo "***** TESTS FAILED. Attempting retry."; $RUN_TESTS; } \
+              || { echo "***** TESTS FAILED. Attempting final retry."; $RUN_TESTS; }
 
-  quickstart-build-and-test:
+  compose-build-and-test:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout Code
-      uses: actions/checkout@v3
-    - name: Set up JDK ${{env.JAVA_VERSION}}
-      uses: actions/setup-java@v3
-      with:
-        distribution: ${{env.JAVA_DISTRIBUTION}}
-        java-version: ${{env.JAVA_VERSION}}
-        maven-version: 3.9.5
-        cache: 'maven'
-    # Allow us to use the "--squash" option below
-    - name: Turn on Docker experimental features and move Docker data root
-      run: |
-        if [[ -f /etc/docker/daemon.json ]]; then
-          sudo sed -ri 's|\s*}\s*$|, "experimental": true, "data-root": "/mnt/docker" }|' /etc/docker/daemon.json
-        else
-          echo $'{\n    "experimental": true, "data-root": "/mnt/docker"\n}' | sudo tee /etc/docker/daemon.json
-        fi
-        sudo systemctl restart docker
-        echo Docker Experimental Features: $(docker version -f '{{.Server.Experimental}}')
-    # Builds the quickstart docker image and run the query tests
-    - name: Quickstart Query Tests
-      env:
-        DW_DATAWAVE_BUILD_COMMAND: "mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -B -V -e -ntp -Dstyle.color=always -Dmaven.build.cache.enabled=false -Pdev -Ddeploy -Dtar -DskipTests clean package"
-        DOCKER_BUILD_OPTS: "--squash --force-rm"
-        USER_NAME: ${{ secrets.USER_NAME }}
-        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
-      run: |
-        TAG=$(mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -q -N -Dmaven.build.cache.enabled=false -Dexec.executable='echo' -Dexec.args='${project.version}' exec:exec)
-        contrib/datawave-quickstart/docker/docker-build.sh ${TAG} --docker-opts "${DOCKER_BUILD_OPTS}"
+      - name: Checkout Code
+        uses: action/checkout@v2
+      - name: Set up JDK ${{env.JAVA_VERSION}}
+        uses: actions/setup-java@v3
+        with:
+          distribution: ${{env.JAVA_DISTRIBUTION}}
+          java-version: ${{env.JAVA_VERSION}}
+          maven-version: 3.9.5
+      # Starts up docker services and runs test queries
+      - name: Start up docker quickstart services and run test
+        uses: docker/login-action@v2
+        with:
+          USER_NAME: ${{ secrets.USER_NAME }}
+          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
+      - name: Check and install Docker Compose
+        run: |
+          if ! [ -x "$(command -v docker-compose)" ]; then
+            sudo apt-get update
+            sudo apt-get install -y docker-compose
+          fi
+      - name: Build and run Docker Compose
+        run: |
+          docker-compose up -d
+      - name: Run TestAll script
+        id: test_all
+        run: |
+          docker-compose -f docker/docker-compose.yml exec web docker/scripts/testAll.sh || echo "Tests failed"
+      - name: Tear down Docker Compose
+        run: |
+          docker-compose down
+      - name: Create test badge
+        if: ${{ steps.test_all.outcome == 'failure' }}
+        run: |
+          echo "![Test Status](https://img.shields.io/badge/tests-failing-red)" > test-status-badge.md
+        continue-on-error: true
+
+#  quickstart-build-and-test:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Checkout Code
+#        uses: actions/checkout@v3
+#      - name: Set up JDK ${{env.JAVA_VERSION}}
+#        uses: actions/setup-java@v3
+#        with:
+#          distribution: ${{env.JAVA_DISTRIBUTION}}
+#          java-version: ${{env.JAVA_VERSION}}
+#          maven-version: 3.9.5
+#          cache: 'maven'
+#      # Allow us to use the "--squash" option below
+#      - name: Turn on Docker experimental features and move Docker data root
+#        run: |
+#          if [[ -f /etc/docker/daemon.json ]]; then
+#            sudo sed -ri 's|\s*}\s*$|, "experimental": true, "data-root": "/mnt/docker" }|' /etc/docker/daemon.json
+#          else
+#            echo $'{\n    "experimental": true, "data-root": "/mnt/docker"\n}' | sudo tee /etc/docker/daemon.json
+#          fi
+#          sudo systemctl restart docker
+#          echo Docker Experimental Features: $(docker version -f '{{.Server.Experimental}}')
+#      # Builds the quickstart docker image and run the query tests
+#      - name: Quickstart Query Tests
+#        env:
+#          DW_DATAWAVE_BUILD_COMMAND: "mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -B -V -e -ntp -Dstyle.color=always -Dmaven.build.cache.enabled=false -Pdev -Ddeploy -Dtar -DskipTests clean package"
+#          DOCKER_BUILD_OPTS: "--squash --force-rm"
+#          USER_NAME: ${{ secrets.USER_NAME }}
+#          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
+#        run: |
+#          TAG=$(mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -q -N -Dmaven.build.cache.enabled=false -Dexec.executable='echo' -Dexec.args='${project.version}' exec:exec)
+#          contrib/datawave-quickstart/docker/docker-build.sh ${TAG} --docker-opts "${DOCKER_BUILD_OPTS}"
 
   compose-build-and-test-latest-snapshots:
     runs-on: ubuntu-latest
